on: [push, pull_request]

jobs:
  example:
    runs-on: ubuntu-latest
    name: Executes Linting
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python path
        uses: "PYTHONPATH=$top_dir/taketwo-webapi; export PYTHONPATH"  

      - name: Run Super-Linter
        uses: github/super-linter@v4.9.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PYTHON_PYLINT_CONFIG_FILE: .pylintrc
          LINTER_RULES_PATH: /.github/linters
